'use strict';

// PDF report generation service
// Uses puppeteer to generate PDFs from HTML templates

const config = require('../config');

/**
 * Generate PDF report for a task
 * @param {Object} task - Task object
 * @param {Array} results - Array of results
 * @returns {Buffer} PDF buffer
 */
async function generateReport(task, results) {
	// Dynamic import for puppeteer (only load when needed)
	const puppeteer = require('puppeteer');
	
	const latestResult = results[0];
	const issues = latestResult?.results || [];
	
	const errorCount = issues.filter(i => i.type === 'error').length;
	const warningCount = issues.filter(i => i.type === 'warning').length;
	const noticeCount = issues.filter(i => i.type === 'notice').length;

	const html = `
		<!DOCTYPE html>
		<html>
		<head>
			<meta charset="utf-8">
			<title>Accessibility Report - ${task.name}</title>
			<style>
				* {
					box-sizing: border-box;
					margin: 0;
					padding: 0;
				}
				body {
					font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
					font-size: 14px;
					line-height: 1.6;
					color: #333;
					padding: 40px;
				}
				h1 {
					font-size: 24px;
					margin-bottom: 8px;
					color: #1a1a1a;
				}
				h2 {
					font-size: 18px;
					margin: 24px 0 12px;
					color: #333;
					border-bottom: 2px solid #228be6;
					padding-bottom: 4px;
				}
				.meta {
					color: #666;
					margin-bottom: 24px;
				}
				.stats {
					display: flex;
					gap: 24px;
					margin-bottom: 24px;
				}
				.stat {
					flex: 1;
					padding: 16px;
					background: #f5f5f5;
					border-radius: 8px;
					text-align: center;
				}
				.stat-value {
					font-size: 32px;
					font-weight: bold;
				}
				.stat-label {
					font-size: 12px;
					color: #666;
					text-transform: uppercase;
				}
				.score { color: ${latestResult?.score >= 80 ? '#40c057' : '#fab005'}; }
				.errors { color: #fa5252; }
				.warnings { color: #fab005; }
				.notices { color: #228be6; }
				
				.issue {
					border: 1px solid #ddd;
					border-radius: 8px;
					padding: 16px;
					margin-bottom: 12px;
				}
				.issue-header {
					display: flex;
					align-items: center;
					gap: 8px;
					margin-bottom: 8px;
				}
				.issue-type {
					padding: 2px 8px;
					border-radius: 4px;
					font-size: 12px;
					font-weight: 500;
					text-transform: uppercase;
				}
				.type-error { background: #ffe0e0; color: #c00; }
				.type-warning { background: #fff3cd; color: #856404; }
				.type-notice { background: #d1ecf1; color: #0c5460; }
				
				.issue-message {
					font-weight: 500;
					margin-bottom: 8px;
				}
				.issue-code {
					font-family: monospace;
					font-size: 12px;
					color: #666;
					margin-bottom: 8px;
				}
				.issue-context {
					background: #f5f5f5;
					padding: 8px;
					border-radius: 4px;
					font-family: monospace;
					font-size: 11px;
					overflow: hidden;
					white-space: pre-wrap;
					word-wrap: break-word;
				}
				
				.footer {
					margin-top: 40px;
					padding-top: 16px;
					border-top: 1px solid #ddd;
					color: #666;
					font-size: 12px;
					text-align: center;
				}
			</style>
		</head>
		<body>
			<h1>Accessibility Report</h1>
			<div class="meta">
				<strong>${task.name}</strong><br>
				${task.url}<br>
				Standard: ${task.standard} | Generated: ${new Date().toLocaleString()}
			</div>
			
			<div class="stats">
				<div class="stat">
					<div class="stat-value score">${latestResult?.score || 0}</div>
					<div class="stat-label">Score</div>
				</div>
				<div class="stat">
					<div class="stat-value errors">${errorCount}</div>
					<div class="stat-label">Errors</div>
				</div>
				<div class="stat">
					<div class="stat-value warnings">${warningCount}</div>
					<div class="stat-label">Warnings</div>
				</div>
				<div class="stat">
					<div class="stat-value notices">${noticeCount}</div>
					<div class="stat-label">Notices</div>
				</div>
			</div>
			
			<h2>Issues Found (${issues.length})</h2>
			
			${issues.slice(0, 50).map(issue => `
				<div class="issue">
					<div class="issue-header">
						<span class="issue-type type-${issue.type}">${issue.type}</span>
						<span class="issue-code">${issue.code}</span>
					</div>
					<div class="issue-message">${escapeHtml(issue.message)}</div>
					${issue.context ? `
						<div class="issue-context">${escapeHtml(issue.context.substring(0, 200))}</div>
					` : ''}
				</div>
			`).join('')}
			
			${issues.length > 50 ? `
				<p style="color: #666; font-style: italic;">
					Showing 50 of ${issues.length} issues. View full results in the dashboard.
				</p>
			` : ''}
			
			<div class="footer">
				Generated by WCAG Monitor | ${config.frontendUrl}
			</div>
		</body>
		</html>
	`;

	const browser = await puppeteer.launch({
		headless: 'new',
		args: ['--no-sandbox', '--disable-setuid-sandbox']
	});

	try {
		const page = await browser.newPage();
		await page.setContent(html, { waitUntil: 'networkidle0' });
		
		const pdfBuffer = await page.pdf({
			format: 'A4',
			margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' },
			printBackground: true
		});

		return pdfBuffer;
	} finally {
		await browser.close();
	}
}

function escapeHtml(text) {
	if (!text) return '';
	return text
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&#039;');
}

module.exports = {
	generateReport
};
